name: transcriptomeDockerPipe
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - fastqc=0.12.1
  - trimmomatic=0.39
  - openjdk=11
  - hisat2=2.2.1
  - samtools=1.20
  - stringtie=3.0.0
  - gffcompare=0.11.2
  - python=3.11
  - pandas
  - gffread=0.12.7
  
  
